speaker_introduction_task:
  description: >
    Craft personalized speaker introductions, including each speaker’s background,
    achievements, and speaking topics. Ensure the introductions capture the speaker's
    expertise and set the tone for their presentation.

    Include details from prior interactions or known preferences where applicable.
    Speaker: {speaker_name}
    Company: {company_name}
    Event: {event_context}

  expected_output: >
    Professionally written introductions for each speaker, including a brief
    overview of their background, key achievements, and areas of expertise.
    Each introduction should be engaging and appropriately tailored to the event audience.


company_showcase_task:
  description: >
    Prepare concise and impactful company presentations for each speaker or company,
    highlighting their key offerings, unique selling points, and real-world impact.
    Ensure each presentation is personalized based on the audience profile and event context.

    Company: {company_name}
    Event: {event_context}

  expected_output: >
    Clear, compelling company presentations for each speaker’s organization, including
    key features, benefits, and differentiators. Each presentation should be concise
    yet informative, tailored to the audience's interests and the event’s theme.


link_sharing_task:
  description: >
    Generate and organize relevant links for each speaker and their companies,
    including company products, product pages, demos, and related resources.
    Ensure links are contextually appropriate and easy to access during the event.

    Consider prior interactions and known audience interests.
    Speaker: {speaker_name}
    Company: {company_name}
    Event: {event_context}

  expected_output: >
    A list of ready-to-share links, including product demos, speaker profiles,
    and relevant resources. Each link should include a short, context-appropriate
    description to guide the audience towards the intended action.

summary_task:
  description: >
    Combine the outputs from the speaker introductions, product showcases, and link sharing tasks
    to create cohesive event summaries. Ensure the summaries capture the key points of each speaker,
    highlight their product offerings, and include relevant links for audience engagement.

    Use inputs from:
    - Speaker Introductions: {speaker_introductions}
    - Product Pitches: {product_pitches}
    - Link Lists: {link_lists}

    Event Context: {event_context}

  expected_output: >
    Comprehensive summaries that integrate the speaker backgrounds, product highlights,
    and relevant links into a single, polished document or script. The summaries should
    be engaging, informative, and seamlessly flow from one topic to the next, ready for
    live presentation or scripted delivery.
