summary_task:
  description: >
    Combine speaker introductions and company showcases into concise event summaries. 
    Highlight key speaker points, company offerings, and include relevant links.

    As a manager agent, integrate all information into a concise report.

    Speaker: {speaker}
    Company: {company}
    Event: {event}
    Speaker Introduction: {speaker_introduction}
    Company Showcase: {company_showcase}

  expected_output: >
    Concise summaries integrating speaker backgrounds and company highlights, 
    flowing seamlessly for presentation or delivery.


speaker_introduction_task:
  description: >
    Craft personalized speaker introductions, including each speaker's background,
    achievements, and speaking topics. Ensure the introductions capture the speaker's
    expertise and set the tone for their presentation.

    Include details from prior interactions or known preferences where applicable.
    Speaker: {speaker}
    Company: {company}
    Event: {event}

  expected_output: >
    Professionally written introductions for each speaker, including a brief
    overview of their background, key achievements, and areas of expertise.
    Each introduction should be engaging and appropriately tailored to the event audience.


company_showcase_task:
  description: >
    Prepare concise and impactful company presentations for each speaker or company,
    highlighting their key offerings, unique selling points, and real-world impact.
    Ensure each presentation matches the event context. Include a link to the company
    and its products. 

    Company: {company}
    Event: {event}

  expected_output: >
    Clear, compelling company presentations for each speaker's organization, including
    key features, benefits, and differentiators. Each presentation should be concise
    yet informative, tailored to the audience's interests and the event's theme.
    Include a link to the company or its products. 
